/** @deprecated Use rankings API (/api/rankings/top) instead of this fake data */
export type Division = "Elite" | "Pro" | "Challenger" | "Rookie";
export type City =
  | "Harare"
  | "Bulawayo"
  | "Mutare"
  | "Gweru"
  | "Kwekwe"
  | "Masvingo"
  | "Chitungwiza"
  | "Victoria Falls";
export type FormResult = "W" | "L" | "D";

export type Hardware = {
  controller: string;
  monitor: string;
  console: string;
};

export type Player = {
  id: string;
  rank: number;
  prev: number;
  name: string;
  gamertag: string;
  city: City;
  division: Division;
  points: number;
  wins: number;
  losses: number;
  draws: number;
  goalsFor: number;
  goalsAgainst: number;
  /** Goals per match — primary scoring metric for EA FC. */
  gpm: number;
  form: FormResult[];
  prizeMoney: number;
  winStreak: number;
  hardware: Hardware;
  whatsapp?: string;
  phone?: string;
  discord?: string;
  twitter?: string;
  twitch?: string;
  instagram?: string;
};

export const PLAYERS: Player[] = [
  {
    id: "p01",
    rank: 1,
    prev: 2,
    name: "Wilfred Chigwende",
    gamertag: "WILFY-Z",
    city: "Harare",
    division: "Elite",
    points: 3120,
    wins: 84,
    losses: 9,
    draws: 7,
    goalsFor: 312,
    goalsAgainst: 78,
    gpm: 3.12,
    form: ["W", "W", "W", "D", "W"],
    prizeMoney: 8400,
    winStreak: 12,
    hardware: {
      controller: "Sony DualSense Edge",
      monitor: 'BenQ Zowie XL2566K 360Hz 25"',
      console: "PS5 Pro",
    },
    whatsapp: "+263 77 123 4567",
    phone: "+263 71 123 4567",
    discord: "wilfy_z",
    twitter: "@WILFY_Z",
    twitch: "wilfy_z",
    instagram: "@wilfy_z",
  },
  {
    id: "p02",
    rank: 2,
    prev: 1,
    name: "Ashly Marimo",
    gamertag: "ASH-MAR",
    city: "Bulawayo",
    division: "Elite",
    points: 3085,
    wins: 80,
    losses: 11,
    draws: 9,
    goalsFor: 298,
    goalsAgainst: 82,
    gpm: 2.98,
    form: ["W", "L", "W", "W", "W"],
    prizeMoney: 6200,
    winStreak: 4,
    hardware: {
      controller: "Sony DualSense Edge",
      monitor: 'LG UltraGear 27" 240Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 234 5678",
    phone: "+263 71 234 5678",
    discord: "ash_mar",
    twitter: "@ASH_MAR",
    twitch: "ash_marimo",
  },
  {
    id: "p03",
    rank: 3,
    prev: 3,
    name: "Kundai Guvaza",
    gamertag: "KUNDAI",
    city: "Harare",
    division: "Elite",
    points: 2980,
    wins: 76,
    losses: 14,
    draws: 8,
    goalsFor: 281,
    goalsAgainst: 96,
    gpm: 2.87,
    form: ["W", "W", "D", "W", "L"],
    prizeMoney: 4500,
    winStreak: 0,
    hardware: {
      controller: "Scuf Reflex Pro",
      monitor: 'Samsung Odyssey G7 27"',
      console: "PS5",
    },
    whatsapp: "+263 77 345 6789",
    phone: "+263 71 345 6789",
    discord: "kundai_g",
    twitter: "@KUNDAI_FC",
    instagram: "@kundai_g",
  },
  {
    id: "p04",
    rank: 4,
    prev: 6,
    name: "Farai Chikomo",
    gamertag: "FARABALL",
    city: "Mutare",
    division: "Elite",
    points: 2842,
    wins: 71,
    losses: 16,
    draws: 12,
    goalsFor: 264,
    goalsAgainst: 102,
    gpm: 2.67,
    form: ["W", "W", "W", "W", "W"],
    prizeMoney: 3100,
    winStreak: 9,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'AOC 24" 165Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 456 7890",
    phone: "+263 71 456 7890",
    discord: "faraball",
    twitch: "faraball_zw",
    instagram: "@faraball",
  },
  {
    id: "p05",
    rank: 5,
    prev: 4,
    name: "Munashe Dube",
    gamertag: "MUNA10",
    city: "Bulawayo",
    division: "Elite",
    points: 2790,
    wins: 69,
    losses: 17,
    draws: 11,
    goalsFor: 251,
    goalsAgainst: 110,
    gpm: 2.59,
    form: ["L", "W", "W", "D", "L"],
    prizeMoney: 2800,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'BenQ Mobiuz 27"',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
    discord: "muna_10",
    twitter: "@MUNA10_ZW",
  },
  {
    id: "p06",
    rank: 6,
    prev: 5,
    name: "Rufaro Banda",
    gamertag: "ZW_RUFA",
    city: "Gweru",
    division: "Pro",
    points: 2640,
    wins: 65,
    losses: 19,
    draws: 13,
    goalsFor: 240,
    goalsAgainst: 121,
    gpm: 2.47,
    form: ["W", "L", "W", "W", "D"],
    prizeMoney: 1900,
    winStreak: 2,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Dell S2522HG 240Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p07",
    rank: 7,
    prev: 9,
    name: "Tatenda Ncube",
    gamertag: "TATENDOO",
    city: "Bulawayo",
    division: "Pro",
    points: 2588,
    wins: 63,
    losses: 20,
    draws: 14,
    goalsFor: 232,
    goalsAgainst: 130,
    gpm: 2.39,
    form: ["W", "W", "W", "L", "W"],
    prizeMoney: 1600,
    winStreak: 3,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'AOC 27" 144Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p08",
    rank: 8,
    prev: 7,
    name: "Panashe Marange",
    gamertag: "PANA-X",
    city: "Harare",
    division: "Pro",
    points: 2510,
    wins: 60,
    losses: 22,
    draws: 14,
    goalsFor: 220,
    goalsAgainst: 138,
    gpm: 2.29,
    form: ["L", "D", "W", "L", "W"],
    prizeMoney: 1400,
    winStreak: 0,
    hardware: {
      controller: "Scuf Reflex",
      monitor: 'LG 24" 144Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p09",
    rank: 9,
    prev: 8,
    name: "Simba Madzima",
    gamertag: "SIMBA-FC",
    city: "Chitungwiza",
    division: "Pro",
    points: 2470,
    wins: 58,
    losses: 23,
    draws: 15,
    goalsFor: 215,
    goalsAgainst: 142,
    gpm: 2.24,
    form: ["W", "W", "L", "D", "L"],
    prizeMoney: 1100,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'AOC 24" 144Hz',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p10",
    rank: 10,
    prev: 12,
    name: "Blessing Tafara",
    gamertag: "BLESS-9",
    city: "Mutare",
    division: "Pro",
    points: 2410,
    wins: 56,
    losses: 24,
    draws: 16,
    goalsFor: 208,
    goalsAgainst: 148,
    gpm: 2.17,
    form: ["W", "W", "D", "W", "W"],
    prizeMoney: 950,
    winStreak: 5,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Acer Nitro 24"',
      console: "PS5",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p11",
    rank: 11,
    prev: 10,
    name: "Tapiwa Gono",
    gamertag: "TAPS",
    city: "Harare",
    division: "Pro",
    points: 2360,
    wins: 54,
    losses: 25,
    draws: 17,
    goalsFor: 200,
    goalsAgainst: 154,
    gpm: 2.08,
    form: ["L", "W", "L", "D", "W"],
    prizeMoney: 800,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'AOC 24" 75Hz',
      console: "PS4 Pro",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p12",
    rank: 12,
    prev: 11,
    name: "Nyasha Chinyemba",
    gamertag: "NY-X",
    city: "Kwekwe",
    division: "Challenger",
    points: 2280,
    wins: 51,
    losses: 27,
    draws: 18,
    goalsFor: 188,
    goalsAgainst: 162,
    gpm: 1.96,
    form: ["L", "L", "W", "D", "W"],
    prizeMoney: 600,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Generic 24" 60Hz',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p13",
    rank: 13,
    prev: 14,
    name: "Tawanda Pedzisai",
    gamertag: "TAWA-FC",
    city: "Masvingo",
    division: "Challenger",
    points: 2210,
    wins: 49,
    losses: 28,
    draws: 19,
    goalsFor: 180,
    goalsAgainst: 168,
    gpm: 1.88,
    form: ["W", "D", "W", "W", "L"],
    prizeMoney: 500,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Generic 24" 75Hz',
      console: "PS4 Pro",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p14",
    rank: 14,
    prev: 13,
    name: "Tariro Hove",
    gamertag: "T-HOVE",
    city: "Harare",
    division: "Challenger",
    points: 2150,
    wins: 47,
    losses: 30,
    draws: 19,
    goalsFor: 174,
    goalsAgainst: 175,
    gpm: 1.81,
    form: ["L", "L", "D", "L", "W"],
    prizeMoney: 420,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'AOC 22"',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p15",
    rank: 15,
    prev: 18,
    name: "Tinodaishe Zhou",
    gamertag: "TINO-X",
    city: "Bulawayo",
    division: "Challenger",
    points: 2090,
    wins: 45,
    losses: 31,
    draws: 20,
    goalsFor: 168,
    goalsAgainst: 180,
    gpm: 1.75,
    form: ["W", "W", "W", "L", "W"],
    prizeMoney: 380,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Generic 22"',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p16",
    rank: 16,
    prev: 15,
    name: "Anesu Mabhena",
    gamertag: "ANE-SU",
    city: "Harare",
    division: "Challenger",
    points: 2030,
    wins: 43,
    losses: 33,
    draws: 20,
    goalsFor: 162,
    goalsAgainst: 188,
    gpm: 1.69,
    form: ["L", "D", "L", "W", "L"],
    prizeMoney: 300,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Generic 22"',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p17",
    rank: 17,
    prev: 16,
    name: "Brian Mhuri",
    gamertag: "B-MHURI",
    city: "Victoria Falls",
    division: "Rookie",
    points: 1950,
    wins: 41,
    losses: 35,
    draws: 20,
    goalsFor: 156,
    goalsAgainst: 195,
    gpm: 1.63,
    form: ["L", "W", "L", "L", "D"],
    prizeMoney: 200,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: '1080p TV',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p18",
    rank: 18,
    prev: 17,
    name: "Ngonidzashe Bere",
    gamertag: "NGONI",
    city: "Mutare",
    division: "Rookie",
    points: 1880,
    wins: 39,
    losses: 36,
    draws: 21,
    goalsFor: 150,
    goalsAgainst: 200,
    gpm: 1.56,
    form: ["L", "L", "L", "D", "W"],
    prizeMoney: 150,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: '1080p TV',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p19",
    rank: 19,
    prev: 19,
    name: "Tafadzwa Mlilo",
    gamertag: "TAFFY",
    city: "Gweru",
    division: "Rookie",
    points: 1810,
    wins: 37,
    losses: 38,
    draws: 21,
    goalsFor: 144,
    goalsAgainst: 208,
    gpm: 1.50,
    form: ["L", "D", "L", "L", "D"],
    prizeMoney: 100,
    winStreak: 0,
    hardware: {
      controller: "Sony DualSense",
      monitor: 'Generic 22"',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
  {
    id: "p20",
    rank: 20,
    prev: 20,
    name: "Wayne Chivasa",
    gamertag: "W-CHIVA",
    city: "Chitungwiza",
    division: "Rookie",
    points: 1740,
    wins: 35,
    losses: 40,
    draws: 21,
    goalsFor: 138,
    goalsAgainst: 215,
    gpm: 1.44,
    form: ["L", "L", "L", "L", "W"],
    prizeMoney: 75,
    winStreak: 1,
    hardware: {
      controller: "Sony DualSense",
      monitor: '1080p TV',
      console: "PS4",
    },
    whatsapp: "+263 77 000 0000",
    phone: "+263 71 000 0000",
  },
];

export const CITIES: City[] = [
  "Harare",
  "Bulawayo",
  "Mutare",
  "Gweru",
  "Kwekwe",
  "Masvingo",
  "Chitungwiza",
  "Victoria Falls",
];

export const DIVISIONS: Division[] = ["Elite", "Pro", "Challenger", "Rookie"];

export function cityTag(city: string): string {
  const map: Record<string, string> = {
    Harare: "HAR", Bulawayo: "BUL", Mutare: "MUT", Gweru: "GWE",
    Kwekwe: "KWE", Masvingo: "MSV", Chitungwiza: "CHI", "Victoria Falls": "VFL",
  };
  return map[city] ?? city.slice(0, 3).toUpperCase();
}
